<?php
//ini_set('display_errors', 1);
include('classFunctionStorage.php');
	
if ($_POST['cable_air_cable_data_city_eng']) {
  $selectedCity= $_POST['cable_air_cable_data_city_eng'];
} else {
  $selectedCity = $_REQUEST['cable_air_cable_data_city_eng'];
}  
	//$linkArchive = "'".'<a href='.'"'.'http://'.$_SERVER['SERVER_ADDR'].'/qgis-ck/tmp/archive/'.$selectedCity.'/air/'."'".'||tmp.progect_number||'."'".'" target="_blank">посилання на архів</a>'."'";
$linkArchive = "'".'https://'.$_SERVER['SERVER_ADDR'].'/qgis-ck/tmp/archive/'.$selectedCity."/air/'".'||tmp.progect_number||'."'/'";
$promeLink = "/tmp/";
$secondaryLink = "/var/www/QGIS-Web-Client-master/site/csv/archive/";
$fileExtention ="_cable_air.csv";
$files = fileExistenceCheck($promeLink, $secondaryLink, $selectedCity, $fileExtention)['files'];
$linkStorage = fileExistenceCheck($promeLink, $secondaryLink, $selectedCity, $fileExtention)['linkStorage'];
$newDBrequest = new dbConnSetClass;
if ($files) {
  foreach($files as $file) {
    $str_file = (string)$file;
    if ($str_file !== '.' && $str_file !== '..') {
      //print_r($str_file);
      if ($str_file == $selectedCity.$fileExtention) {
        $query = "CREATE temp TABLE tmp (id serial,table_id varchar(100), cable_progect_link varchar(100), cable_mount_date varchar(100), cable_id varchar(100), cable_type varchar(100), cable_short_type_description varchar(100), cable_description varchar(100),  progect_number varchar(100), executive_doc_state varchar(100), cable_purpose varchar(100),  cubic_start_street varchar(100), cubic_start_house_num varchar(100), cubic_start_house_entrance_num varchar(100),link_fiber_welding_start varchar(100), cubic_end_street varchar(100), cubic_end_house_num varchar(100),  cubic_end_house_entrance_num varchar(100), link_fiber_welding_end varchar(100), total_cable_length varchar(100), notes2 varchar(100), rezerve1 varchar(100),  rezerve2 varchar(100),  rezerve3 varchar(100),  rezerve4 varchar(100), cubic_code_start varchar(100),  cubic_name_start varchar(100),  cubic_coment_start varchar(100),  cubic_code_end varchar(100),  cubic_name_end varchar(100),  cubic_coment_end varchar(100)); select copy_for_testuser('tmp (table_id , cable_progect_link , cable_mount_date ,  cable_id , cable_type , cable_short_type_description , cable_description ,  progect_number , executive_doc_state , cable_purpose , cubic_start_street , cubic_start_house_num,  cubic_start_house_entrance_num , link_fiber_welding_start , cubic_end_street , cubic_end_house_num ,  cubic_end_house_entrance_num , link_fiber_welding_end ,  total_cable_length , notes2 , rezerve1 , rezerve2 , rezerve3 , rezerve4 ,cubic_code_start,  cubic_name_start,  cubic_coment_start,  cubic_code_end,  cubic_name_end,  cubic_coment_end )', ".$linkStorage.", ';', 'windows-1251') ; 

        UPDATE ".$selectedCity.".".$selectedCity."_cable_air SET cable_progect_link  = null,cable_mount_date   = null  , cable_id   = null  , cable_type   = null  , cable_short_type_description   = null  , cable_description   = null, progect_number   = null , executive_doc_state   = null, cable_purpose  = null , cubic_start_house_id   = null  , cubic_start_street   = null  , cubic_start_house_num   = null , cubic_start_house_entrance_num   = null  , link_fiber_welding_start   = null  ,  cubic_end_house_id   = null  , cubic_end_street   = null  , cubic_end_house_num   = null , cubic_end_house_entrance_num   = null  , link_fiber_welding_end   = null  ,  total_cable_length   = null ,  notes2   = null , rezerve1   = null , rezerve2   = null , rezerve3   = null , rezerve4   = null, cubic_code_start = null, cubic_name_start = null, cubic_coment_start = null, cubic_code_end = null, cubic_name_end = null, cubic_coment_end = null from tmp where ".$selectedCity."_cable_air.table_id = tmp.table_id and    tmp.cable_mount_date  is null and tmp.cable_id  is null and tmp.cable_type is null and tmp.cable_short_type_description  is null and tmp.cable_description  is null and  tmp.progect_number  is null and tmp.executive_doc_state   is null and  tmp.cable_purpose  is null and  tmp.cubic_start_street  is null and tmp.cubic_start_house_num  is null and  tmp.cubic_start_house_entrance_num   is null and  tmp.cubic_end_street  is null and tmp.cubic_end_house_num   is null and  tmp.cubic_end_house_entrance_num   is null and  tmp.total_cable_length  is null and  tmp.notes2  is null and  tmp.rezerve1  is null and  tmp.rezerve2  is null and  tmp.rezerve3  is null and  tmp.rezerve4  is null and tmp.cubic_code_start is null and tmp.cubic_name_start is null and   tmp.cubic_coment_start is null and tmp.cubic_code_end is null and tmp.cubic_name_end is null and tmp.cubic_coment_end is null; 

        UPDATE ".$selectedCity.".".$selectedCity."_cable_air SET  cable_progect_link  = ".$linkArchive.",cable_mount_date   = tmp.cable_mount_date  , cable_id   = tmp.cable_id  , cable_type   = tmp.cable_type  , cable_short_type_description   = tmp.cable_short_type_description  , cable_description   = tmp.cable_description  , progect_number   = tmp.progect_number  , executive_doc_state   = tmp.executive_doc_state  , cable_purpose  = tmp.cable_purpose , cubic_start_street   = tmp.cubic_start_street  , cubic_start_house_num   = tmp.cubic_start_house_num  , cubic_start_house_entrance_num   = tmp.cubic_start_house_entrance_num  , cubic_end_street   = tmp.cubic_end_street  , cubic_end_house_num   = tmp.cubic_end_house_num  , cubic_end_house_entrance_num   = tmp.cubic_end_house_entrance_num  ,  total_cable_length   = tmp.total_cable_length  ,  notes2   = tmp.notes2  , rezerve1   = tmp.rezerve1  , rezerve2   = tmp.rezerve2  , rezerve3   = tmp.rezerve3  , rezerve4   = tmp.rezerve4 FROM tmp WHERE ".$selectedCity.".".$selectedCity."_cable_air.table_id = tmp.table_id and tmp.table_id is not null and tmp.cable_type is not null and tmp.cable_short_type_description is not null and tmp.cable_description is not null;DROP TABLE tmp;";
        $queryArrayKeys = false;
        echo $query;
        $retuenedArray = $newDBrequest -> dbConnect($query, $queryArrayKeys, true);
        
      }
    } 
  }
}
$query = "UPDATE ".$selectedCity.".".$selectedCity."_cable_air set geom_start_point = ST_StartPoint(geom_cable), geom_end_point = ST_EndPoint(geom_cable) where geom_cable is not null;";
$queryArrayKeys = false;
echo $query;
$retuenedArray = $newDBrequest -> dbConnect($query, $queryArrayKeys, true);
$query = "UPDATE ".$selectedCity.".".$selectedCity."_cable_air set cubic_code_start = ".$selectedCity."_ctv_topology.cubic_code, cubic_name_start = ".$selectedCity."_ctv_topology.cubic_name, cubic_coment_start = ".$selectedCity."_ctv_topology.cubic_coment, geom_start_point = ".$selectedCity."_ctv_topology.equipment_geom  from ".$selectedCity.".".$selectedCity."_ctv_topology where geom_cable is not null and ST_Equals(ST_StartPoint(geom_cable),".$selectedCity."_ctv_topology.equipment_geom) and ".$selectedCity."_ctv_topology.equipment_geom is not null and ".$selectedCity."_cable_air.cubic_code_start is null and ".$selectedCity."_cable_air.cubic_name_start is null; 
UPDATE ".$selectedCity.".".$selectedCity."_cable_air set cubic_code_end = ".$selectedCity."_ctv_topology.cubic_code, cubic_name_end = ".$selectedCity."_ctv_topology.cubic_name, cubic_coment_end = ".$selectedCity."_ctv_topology.cubic_coment, geom_end_point = ".$selectedCity."_ctv_topology.equipment_geom from ".$selectedCity.".".$selectedCity."_ctv_topology where geom_cable is not null and ST_Equals(ST_EndPoint(geom_cable),".$selectedCity."_ctv_topology.equipment_geom) and ".$selectedCity."_ctv_topology.equipment_geom is not null and ".$selectedCity."_cable_air.cubic_code_end is null and ".$selectedCity."_cable_air.cubic_name_end is null;";
$queryArrayKeys = false;
echo $query;
$retuenedArray = $newDBrequest -> dbConnect($query, $queryArrayKeys, true);
$query = "UPDATE ".$selectedCity.".".$selectedCity."_cable_air set geom_start_point = ".$selectedCity."_ctv_topology.equipment_geom from ".$selectedCity.".".$selectedCity."_ctv_topology where ".$selectedCity.".".$selectedCity."_cable_air.cubic_code_start is not null and ".$selectedCity."_ctv_topology.equipment_geom is not null and ".$selectedCity."_cable_air.cubic_code_start = ".$selectedCity."_ctv_topology.cubic_code;UPDATE ".$selectedCity.".".$selectedCity."_cable_air set geom_end_point = ".$selectedCity."_ctv_topology.equipment_geom from ".$selectedCity.".".$selectedCity."_ctv_topology where ".$selectedCity.".".$selectedCity."_cable_air.cubic_code_end is not null and ".$selectedCity."_ctv_topology.equipment_geom is not null and ".$selectedCity."_cable_air.cubic_code_end = ".$selectedCity."_ctv_topology.cubic_code;UPDATE ".$selectedCity.".".$selectedCity."_cable_air_cable_geom set geom = cabs.geom from (select ST_SetPoint(ST_SetPoint(geom, ST_NPoints(geom)-1, ".$selectedCity."_cable_air.geom_end_point), 0, ".$selectedCity."_cable_air.geom_start_point) as geom, ".$selectedCity."_cable_air.table_id  from ".$selectedCity.".".$selectedCity."_cable_air, ".$selectedCity.".".$selectedCity."_cable_air_cable_geom where ".$selectedCity."_cable_air_cable_geom.table_id = ".$selectedCity."_cable_air.table_id and ".$selectedCity."_cable_air_cable_geom.geom is not null and ".$selectedCity."_cable_air.geom_start_point is not null and ".$selectedCity."_cable_air.geom_end_point is not null) cabs where cabs.table_id = ".$selectedCity."_cable_air_cable_geom.table_id ;";
$queryArrayKeys = false;
echo $query;
$retuenedArray = $newDBrequest -> dbConnect($query, $queryArrayKeys, true);
$query = "create temp table tmp as select air.table_id, topo.cubic_code,topo.cubic_name, topo.cubic_coment, topo.equipment_geom, st_dwithin(ST_StartPoint(air.geom_cable),topo.equipment_geom,5) as start_point, st_dwithin(ST_EndPoint(air.geom_cable),topo.equipment_geom,5) as end_point from ".$selectedCity.".".$selectedCity."_cable_air air, ".$selectedCity.".".$selectedCity."_ctv_topology topo where air.geom_cable is not null and topo.equipment_geom is not null and(st_dwithin(ST_StartPoint(air.geom_cable),topo.equipment_geom,5) = true or st_dwithin(ST_EndPoint(air.geom_cable),topo.equipment_geom,5) = true) ;update ".$selectedCity.".".$selectedCity."_cable_air set cubic_code_start = tmp.cubic_code, cubic_name_start = tmp.cubic_name, cubic_coment_start = tmp.cubic_coment, geom_start_point = tmp.equipment_geom from tmp where ".$selectedCity."_cable_air.table_id = tmp.table_id and ".$selectedCity."_cable_air.geom_cable is not null and tmp.start_point = true;update ".$selectedCity.".".$selectedCity."_cable_air set cubic_code_end = tmp.cubic_code, cubic_name_end = tmp.cubic_name, cubic_coment_end = tmp.cubic_coment, geom_end_point = tmp.equipment_geom from tmp where ".$selectedCity."_cable_air.table_id = tmp.table_id and ".$selectedCity."_cable_air.geom_cable is not null and tmp.end_point = true;UPDATE ".$selectedCity.".".$selectedCity."_cable_air_cable_geom set geom = cabs.geom from (select ST_SetPoint(ST_SetPoint(geom, ST_NPoints(geom)-1, ".$selectedCity."_cable_air.geom_end_point), 0, ".$selectedCity."_cable_air.geom_start_point) as geom, ".$selectedCity."_cable_air.table_id  from ".$selectedCity.".".$selectedCity."_cable_air, ".$selectedCity.".".$selectedCity."_cable_air_cable_geom where ".$selectedCity."_cable_air_cable_geom.table_id = ".$selectedCity."_cable_air.table_id and ".$selectedCity."_cable_air_cable_geom.geom is not null and ".$selectedCity."_cable_air.geom_start_point is not null and ".$selectedCity."_cable_air.geom_end_point is not null) cabs where cabs.table_id = ".$selectedCity."_cable_air_cable_geom.table_id;";
$queryArrayKeys = false;
echo $query;
$retuenedArray = $newDBrequest -> dbConnect($query, $queryArrayKeys, true);
?>