# -*- coding: utf-8 -*-
# -*- coding: cp1251 -*-
cities = [['volia.vn','vinnitsa','Вінниця'],
['volia.kh','kharkiv','Харків'],
['volia.sevastopol','sevastopol','Севастополь'],
['volia.kr','kropyvnytskyi','Кропивницький'],
['volia.ck','cherkassy','Черкаси'],
['volia.pl','poltava','Полтава'],
['volia.km','khmelnitsky','Хмельницький'],
['volia.simferopol','simferopol','Сімферополь'],
['volia.sumy','sumy','Суми'],
['volia.dn','donetsk','Донецьк'],
['volia.dp','dnipro','Дніпро'],
['volia.zp','zaporizhia','Запоріжжя'],
['volia.kiev','kiev','Київ'],
['volia.al','alchevsk','Алчевськ'],
['volia.cv','chernivtsi','Чернівці'],
['volia.kherson','kherson','Херсон'],
['volia.krm','kramatorsk','Краматорськ'],
['volia.rv','rivne','Рівне'],
['volia.lviv','lviv','Львів'],
['volia.kryvyirih','kryvyirih','Кривий Ріг'],
['volia.putyvl','putyvl','Путивль'],
['volia.kremenec','kremenets','Кременець'],
['volia.lutsk','lutsk','Луцьк'],
['volia.terebovlia','terebovlya','Теребовля'],
['volia.ternopil','ternopil','Тернопіль'],
['volia.chortkiv.chortkiv','chortkiv','Чортків'],
['volia.illichivsk','Chornomorsk','Іллічівськ'],
['volia.ovidiopol','ovidiopol','Овідіополь'],
['volia.karlivka','karlivka','Карлівка'],
['volia.fas','fastiv','Фастів'],
['volia.makiyivka','makiyivka','Макіївка'],
['volia.volochysk','volochisk','Волочиськ'],
['volia.solonitsevka','solonitsevka','Солоницівка'],
['volia.brovary','brovary', 'Бровари'],
['volia.zhytomyr','zhitomir','Житомир'],
['volia.melitopol','melitopol','Мелітополь'],
['volia.stebnyk','stebnyk','Стебник'],
['volia.odessa','odesa','Одеса'],
['volia.berdychiv','berdychiv', 'Бердичів'],
['volia.ukrainka','ukrainka','Українка'],
['volia.dobrotvir','dobrotvir','Добротвір'],
['volia.truskavets','truskavets','Трускавець'],
['volia.kamianets-podilskyi','kamianets-podilskyi','Кам_янець-Подільський'],
['volia.obukhiv','obukhiv','Обухів'],
['volia.bila-tserkva','bilatserkva', 'Біла Церква'],
['volia.nvm','novomoskovsk','Новомосковськ'],
['volia.ivano-frankivsk','ivanofrankivsk','Івано-Франківськ']]
